version: '2.2'

services:
  ansible-docs-boot:
    image: zzzmahesh/ansible-docs-boot:latest
    restart: on-failure
    ports:
      - 8080:8080
  ansible-playbook-json2yaml:
    image: zzzmahesh/ansible-playbook-json2yaml
    restart: on-failure
    ports:
      - 5000:5000
  ansible-playbook-generator-ui:
    image: zzzmahesh/ansible-playbook-generator-ui:latest
    restart: on-failure
    depends_on:
      ansible-playbook-json2yaml:
        condition: service_started
      ansible-docs-boot:
        condition: service_started
    ports:
      - 80:80
