/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CommandRef } from './commandRef';
import { InputFieldRef } from './inputFieldRef';
import { OutputFieldDTO } from './outputFieldDTO';
export interface CommandDetailsDTO {
    command?: CommandRef;
    inputFields?: Array<InputFieldRef>;
    outputFields?: Array<OutputFieldDTO>;
    optional?: boolean;
    no_log?: boolean;
    task_name?: string;
    delegate_to?: string;
    become?: string;
    become_method?: string;
    with_items?: string;
    when?: string;
    register?: string;
}
