/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ModuleRef } from './moduleRef';
import { SubModuleRef } from './subModuleRef';
export interface CommandRef {
    commandId?: number;
    moduleRef?: ModuleRef;
    subModuleRef?: SubModuleRef;
    command?: string;
    commandDescription?: string;
    synopsis?: string;
    requirements?: string;
    refUrl?: string;
    insertTimestamp?: Date;
    updateTimestamp?: Date;
}
