/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CommandRef } from './commandRef';
export interface InputFieldRef {
    inputFieldId?: number;
    commandRef?: CommandRef;
    fieldName?: string;
    fieldDescription?: string;
    fieldType?: string;
    defaultValue?: string;
    value?: string;
    choices?: string;
    refUrl?: string;
    insertTimestamp?: Date;
    updateTimestamp?: Date;
}
