/**
 * Ansible Playbook JSON to YAML
 * Ansible Playbook JSON to YAML
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BookRequest } from './bookRequest';
export interface BookRequests {
    bookRequest?: {
        [key: string]: BookRequest;
    };
}
